
tasks:
  - init: source mindcloud/bin/activate
    command: pip install --upgrade pip   
             pip install -r requirements.txt





vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.jupyter-keymap
    - ms-python.isort
    - ms-toolsai.jupyter
